package com.zysy.tools.UI;

public enum UIType {
    None,
    HUDLayer,
    BattleLayer,
    BaseMainCityLayer,
    BroadCastLayer,
    MainCityHighLayer,
    SystemBackgroundLayer,
    SystemLayer,
    TopNavigationLayer,
    SystemLayerMid,
    SystemLayerTop,
    ChatLayer,
    DialogBgLayer,
    InteractPuzzleLayer,
    DialogPicLayer,
    DialogMaskingLayer,
    DialogLayer,
    MaltiNpcLayer,
    AwardLayer,
    Masked,
    Tip,
    SystemUnlock,
    FightGuide,
    TopEffectLayer,
    BulletScreen,
    LoadingLayer,
    MsgTip,
    Layer1,
    Layer2,
    GameMasterLayer,
}

